# Generated by Django 5.1.1 on 2024-09-12 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0004_rename_plakat_film_plakaty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='plakaty',
            new_name='plakat',
        ),
    ]
