# Generated by Django 5.1.1 on 2024-09-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmyweb', '0005_rename_plakaty_film_plakat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='plakat',
            field=models.ImageField(blank=True, null=True, upload_to='plakaty'),
        ),
    ]
